### ISSUE TITLE
How to undo react-native swiftify?

### ISSUE THREAD

**Issue by TowhidKashem** [rhdeck/react-native-swift#5]
Hey @rhdeck!

I was using a lib called react-native-track-player which has this lib as a dependency. So I had installed this and ran the command:

> react-native swiftify

And it was great. But now I no longer need that lib and this neither. So can I just remove this lib and delete the `ios/RNPlaceholder.swift` file and the `isSwift: true` from package.json?

Or does that command do more add these 2 things and I need to do more? In that case is there a command to reverse whatever "react-native swiftify" does?

**Comment by rhdeck** [comment]
Those two together should work fine.
